version: '3'
services:
  postgres:
    image: "postgres"
    environment:
      POSTGRES_DB: "movies"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - '5432:5432'
  app:
    depends_on:
      - postgres
    command:
      - python
      - app.py
      - --download
      - --list
      - --year=2018
      - --year=2017
      - --search=The
    build: .
    volumes:
      - .:/app